[package]
name = "tezedge_proxy"
version = "0.1.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.25"
failure = "0.1"
log = "0.4"
simple_logger = "1.6"
crossbeam = "0.7"
hex = "0.4"
lazy_static = "1.4"
bytes = "0.5"
serde_json = "1.0"
itertools = "0.8"
serde = { version="1.0", features=["derive"] }
crypto = { version="*", git = "https://github.com/simplestaking/tezedge" }
networking = { version="*", git = "https://github.com/simplestaking/tezedge" }
tezos_messages = { version="*", git = "https://github.com/simplestaking/tezedge" }
tezos_encoding = { version="*", git = "https://github.com/simplestaking/tezedge" }