[package]
name = "tezedge_proxy"
version = "0.1.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.25.0"
failure = "0.1.6"
log = "0.4.8"
simple_logger = "1.6.0"
state = "0.4.1"
crypto = { version="*", git = "https://github.com/simplestaking/tezedge" }
tezos_messages = { version="*", git = "https://github.com/simplestaking/tezedge" }
networking = { version="*", git = "https://github.com/simplestaking/tezedge" }